# FerrFlow uses itself for versioning

[workspace]
remote = "origin"
branch = "main"

[[package]]
name = "ferrflow"
path = "."
changelog = "CHANGELOG.md"
shared_paths = ["src/"]

[[package.versioned_files]]
path = "Cargo.toml"
format = "toml"

[[package.versioned_files]]
path = "npm/package.json"
format = "json"
